name: Feature Request
description: Suggest a new feature or improvement for FedRAG.
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature to improve FedRAG!
        Please describe your idea in detail below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem or need would this feature solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: How would you like to see this implemented? Feel free to share ideas or API sketches.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered other solutions or workarounds?
